export { default as Home } from './Home/Home.jsx'
export { default as Login } from './Login/Login.jsx'
export { default as Signup } from './Signup/Signup.jsx'
//export { default as Logout } from './Logout/Logout.jsx'
//export { default as Profile } from './Profile/Profile.jsx'
export { default as NotFound } from './Not_Found/NotFound.jsx'
export { default as Results } from './Results/Results.jsx'